$(document).on('turbolinks:load', function() {
  $(document).ready(function() {
    $('#jmap').jmap({
      width: '100%',
      height: '450px',
      dividerColor: '#EFE4A6',
      showPrefectureName: true,
      showRoundedPrefecture: true,
      prefectureNameType: 'full',
      prefectureLineColor: '#EFE4A6',
      prefectureLineHoverColor: '#ffffff',
      prefectureLineWidth: '2px',
      prefectureLineGap: '0px',
      prefectureInnerLineWidth: '1px',
      prefectureInnerLineColor: '#EFE4A6',
      prefectureInnerLineType: 'outset',
      prefectureRadius: '15px',
      prefectureLineY: '2px',
      prefectureLineX: '2px',
      fontSize: '0.9rem',
      fontColor: '#000',
      areas: [
        {code : 1,  name: "北海道", color: "#93b2f5", hoverColor: "#c4d3f5" },
        {code : 2,  name: "青森",   color: "#93b2f5", hoverColor: "#c4d3f5" },
        {code : 3,  name: "岩手",   color: "#93b2f5", hoverColor: "#c4d3f5" },
        {code : 4,  name: "宮城",   color: "#93b2f5", hoverColor: "#c4d3f5" },
        {code : 5,  name: "秋田",   color: "#93b2f5", hoverColor: "#c4d3f5" },
        {code : 6,  name: "山形",   color: "#93b2f5", hoverColor: "#c4d3f5" },
        {code : 7,  name: "福島",   color: "#93b2f5", hoverColor: "#c4d3f5" },
        {code : 8,  name: "茨城",   color: "#7ecfea", hoverColor: "#b7e5f4" },
        {code : 9,  name: "栃木",   color: "#7ecfea", hoverColor: "#b7e5f4" },
        {code : 10, name: "群馬",   color: "#7ecfea", hoverColor: "#b7e5f4" },
        {code : 11, name: "埼玉",   color: "#7ecfea", hoverColor: "#b7e5f4" },
        {code : 12, name: "千葉",   color: "#7ecfea", hoverColor: "#b7e5f4" },
        {code : 13, name: "東京",   color: "#7ecfea", hoverColor: "#b7e5f4" },
        {code : 14, name: "神奈川", color: "#7ecfea", hoverColor: "#b7e5f4" },
        {code : 15, name: "新潟",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 16, name: "富山",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 17, name: "石川",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 18, name: "福井",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 19, name: "山梨",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 20, name: "長野",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 21, name: "岐阜",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 22, name: "静岡",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 23, name: "愛知",   color: "#7cdc92", hoverColor: "#aceebb" },
        {code : 24, name: "三重",   color: "#ffe966", hoverColor: "#fff19c" },
        {code : 25, name: "滋賀",   color: "#ffe966", hoverColor: "#fff19c" },
        {code : 26, name: "京都",   color: "#ffe966", hoverColor: "#fff19c" },
        {code : 27, name: "大阪",   color: "#ffe966", hoverColor: "#fff19c" },
        {code : 28, name: "兵庫",   color: "#ffe966", hoverColor: "#fff19c" },
        {code : 29, name: "奈良",   color: "#ffe966", hoverColor: "#fff19c" },
        {code : 30, name: "和歌山", color: "#ffe966", hoverColor: "#fff19c" },
        {code : 31, name: "鳥取",   color: "#ffcc66", hoverColor: "#ffe0a3" },
        {code : 32, name: "島根",   color: "#ffcc66", hoverColor: "#ffe0a3" },
        {code : 33, name: "岡山",   color: "#ffcc66", hoverColor: "#ffe0a3" },
        {code : 34, name: "広島",   color: "#ffcc66", hoverColor: "#ffe0a3" },
        {code : 35, name: "山口",   color: "#ffcc66", hoverColor: "#ffe0a3" },
        {code : 36, name: "徳島",   color: "#fb9466", hoverColor: "#ffbb9c" },
        {code : 37, name: "香川",   color: "#fb9466", hoverColor: "#ffbb9c" },
        {code : 38, name: "愛媛",   color: "#fb9466", hoverColor: "#ffbb9c" },
        {code : 39, name: "高知",   color: "#fb9466", hoverColor: "#ffbb9c" },
        {code : 40, name: "福岡",   color: "#ffbdbd", hoverColor: "#ffe6e6" },
        {code : 41, name: "佐賀",   color: "#ffbdbd", hoverColor: "#ffe6e6" },
        {code : 42, name: "長崎",   color: "#ffbdbd", hoverColor: "#ffe6e6" },
        {code : 43, name: "熊本",   color: "#ffbdbd", hoverColor: "#ffe6e6" },
        {code : 44, name: "大分",   color: "#ffbdbd", hoverColor: "#ffe6e6" },
        {code : 45, name: "宮崎",   color: "#ffbdbd", hoverColor: "#ffe6e6" },
        {code : 46, name: "鹿児島", color: "#ffbdbd", hoverColor: "#ffe6e6" },
        {code : 47, name: "沖縄",   color: "#ffbdbd", hoverColor: "#ffe6e6" }
      ],
      onSelect : function(e,data){
        location.href = "/search?latest=true&prefecture_id="+(data.code);
      }
    });
  });
});